/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DrugTraceabilityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "drugCount"
      | "drugHistory"
      | "drugs"
      | "getDrugHistory"
      | "getDrugInfo"
      | "getDrugsByOwner"
      | "getUserRole"
      | "isExpired"
      | "registerDrug"
      | "registerUser"
      | "registeredUsers"
      | "transferDrug"
      | "updateDrugStatus"
      | "userRoles"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DrugRegistered"
      | "DrugStatusChanged"
      | "DrugTransferred"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "drugCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "drugHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "drugs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getDrugHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDrugInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDrugsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDrug",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferDrug",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDrugStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userRoles",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drugCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drugHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drugs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDrugHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDrugInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDrugsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDrug",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferDrug",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDrugStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userRoles", data: BytesLike): Result;
}

export namespace DrugRegisteredEvent {
  export type InputTuple = [
    drugId: BigNumberish,
    name: string,
    batchId: string,
    manufacturer: AddressLike
  ];
  export type OutputTuple = [
    drugId: bigint,
    name: string,
    batchId: string,
    manufacturer: string
  ];
  export interface OutputObject {
    drugId: bigint;
    name: string;
    batchId: string;
    manufacturer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrugStatusChangedEvent {
  export type InputTuple = [drugId: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [drugId: bigint, newStatus: bigint];
  export interface OutputObject {
    drugId: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrugTransferredEvent {
  export type InputTuple = [
    drugId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    drugId: bigint,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    drugId: bigint;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [userAddress: AddressLike, role: BigNumberish];
  export type OutputTuple = [userAddress: string, role: bigint];
  export interface OutputObject {
    userAddress: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DrugTraceability extends BaseContract {
  connect(runner?: ContractRunner | null): DrugTraceability;
  waitForDeployment(): Promise<this>;

  interface: DrugTraceabilityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  drugCount: TypedContractMethod<[], [bigint], "view">;

  drugHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  drugs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        batchId: string;
        quantity: bigint;
        manufactureDate: bigint;
        expiryDate: bigint;
        manufacturer: string;
        currentOwner: string;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getDrugHistory: TypedContractMethod<
    [_drugId: BigNumberish],
    [string[]],
    "view"
  >;

  getDrugInfo: TypedContractMethod<
    [_drugId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint
      ] & {
        id: bigint;
        name: string;
        batchId: string;
        quantity: bigint;
        manufactureDate: bigint;
        expiryDate: bigint;
        manufacturer: string;
        currentOwner: string;
        status: bigint;
      }
    ],
    "view"
  >;

  getDrugsByOwner: TypedContractMethod<
    [_owner: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserRole: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  isExpired: TypedContractMethod<[_drugId: BigNumberish], [boolean], "view">;

  registerDrug: TypedContractMethod<
    [
      _name: string,
      _batchId: string,
      _quantity: BigNumberish,
      _manufactureDate: BigNumberish,
      _expiryDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  registerUser: TypedContractMethod<
    [_user: AddressLike, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  registeredUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  transferDrug: TypedContractMethod<
    [_drugId: BigNumberish, _to: AddressLike],
    [void],
    "nonpayable"
  >;

  updateDrugStatus: TypedContractMethod<
    [_drugId: BigNumberish, _status: BigNumberish],
    [void],
    "nonpayable"
  >;

  userRoles: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "drugCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "drugHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "drugs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        batchId: string;
        quantity: bigint;
        manufactureDate: bigint;
        expiryDate: bigint;
        manufacturer: string;
        currentOwner: string;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDrugHistory"
  ): TypedContractMethod<[_drugId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDrugInfo"
  ): TypedContractMethod<
    [_drugId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint
      ] & {
        id: bigint;
        name: string;
        batchId: string;
        quantity: bigint;
        manufactureDate: bigint;
        expiryDate: bigint;
        manufacturer: string;
        currentOwner: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDrugsByOwner"
  ): TypedContractMethod<[_owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserRole"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[_drugId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerDrug"
  ): TypedContractMethod<
    [
      _name: string,
      _batchId: string,
      _quantity: BigNumberish,
      _manufactureDate: BigNumberish,
      _expiryDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [_user: AddressLike, _role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferDrug"
  ): TypedContractMethod<
    [_drugId: BigNumberish, _to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDrugStatus"
  ): TypedContractMethod<
    [_drugId: BigNumberish, _status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userRoles"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "DrugRegistered"
  ): TypedContractEvent<
    DrugRegisteredEvent.InputTuple,
    DrugRegisteredEvent.OutputTuple,
    DrugRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DrugStatusChanged"
  ): TypedContractEvent<
    DrugStatusChangedEvent.InputTuple,
    DrugStatusChangedEvent.OutputTuple,
    DrugStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "DrugTransferred"
  ): TypedContractEvent<
    DrugTransferredEvent.InputTuple,
    DrugTransferredEvent.OutputTuple,
    DrugTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "DrugRegistered(uint256,string,string,address)": TypedContractEvent<
      DrugRegisteredEvent.InputTuple,
      DrugRegisteredEvent.OutputTuple,
      DrugRegisteredEvent.OutputObject
    >;
    DrugRegistered: TypedContractEvent<
      DrugRegisteredEvent.InputTuple,
      DrugRegisteredEvent.OutputTuple,
      DrugRegisteredEvent.OutputObject
    >;

    "DrugStatusChanged(uint256,uint8)": TypedContractEvent<
      DrugStatusChangedEvent.InputTuple,
      DrugStatusChangedEvent.OutputTuple,
      DrugStatusChangedEvent.OutputObject
    >;
    DrugStatusChanged: TypedContractEvent<
      DrugStatusChangedEvent.InputTuple,
      DrugStatusChangedEvent.OutputTuple,
      DrugStatusChangedEvent.OutputObject
    >;

    "DrugTransferred(uint256,address,address,uint256)": TypedContractEvent<
      DrugTransferredEvent.InputTuple,
      DrugTransferredEvent.OutputTuple,
      DrugTransferredEvent.OutputObject
    >;
    DrugTransferred: TypedContractEvent<
      DrugTransferredEvent.InputTuple,
      DrugTransferredEvent.OutputTuple,
      DrugTransferredEvent.OutputObject
    >;

    "UserRegistered(address,uint8)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
