/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DrugTraceability } from "./DrugTraceability";
export * as factories from "./factories";
export { DrugTraceability__factory } from "./factories/DrugTraceability__factory";
